version: 2

jobs:
  build:
    working_directory: ~/arachnid-website

    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run:
          name: 'Update NPM'
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: 'Install Packages'
          command: 'npm ci'

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: 'Build Static HTML'
          command: 'npm run build'

      - run:
          name: 'Compress Build Output'
          command: 'tar -zcvf out.tar.gz .out/'

      - store_artifacts:
          path: out.tar.gz
          destination: out.tar.gz
          
    branches:
      only:
        - master